spring:
  application:
    name: voj-backend-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: voj-backend-user-service
          uri: lb://voj-backend-user-service  # ???????????nacos???
          predicates:
            - Path=/api/user/**
        - id: voj-backend-question-service
          uri: lb://voj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: voj-backend-judge-service
          uri: lb://voj-backend-judge-service
          predicates:
            - Path=/api/judge/**
  main:
    web-application-type: reactive
server:
  port: 8101